Разметка всех станиц
htmlacademy-adaptive/2071609-sedona-27 pull request #2
Opened 2022-11-27 16:44 UTC by Bubleshmig163

2022-11-28 18:07 UTC, captain-zsa reviewed
В общем я проверил только одну страницу и по ней куча ошибок. На основании этих ошибок можно исправить и форму и index вполне себе (а по форме вовсе можно посмотреть вот этот ролик, там идентичная форма, только в cat energy) и пробовать применять принципы бэм правильным образом (и пожалуйста именуй нормально исходя из смысла блока, а не "статистика" причем какая статистика и в каком месте вообще на сайте этом есть статистика – я вообще не знаю).

Собственно ролик: https://youtu.be/jq2DdcEPPA0

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +            <a href="catalog.html">
Мы в каталоге, зачем нам с каталога на каталог ссылка?))

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +    <a class="main-header__logo">
А вот с логотипа на главную ссылку бы как раз таки хотелось.

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +    <img src="/source/img/form-catalog-main-sedona-mountain.jpg" width="320" height="158" alt="Sedona mountain">
Эм.... картинка гор вообще полностью фоновая и икак не должна тут стоять от слова совсем. Похоже тебе надо изучить что является декоративным изображением а что контентным

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +    <img src="/source/img/form-catalog-main-sedona-mountain.jpg" width="320" height="158" alt="Sedona mountain">
Более того пути мы никогда не пишем такие дикие. Мы пишем относительно файла нашего в котором у нас разметка. Разметка лежит рядом с папкой картинок значит путь img/картинка а не как у тебя со слэшем в начале и с тем более source. По путям опять же в учебнике есть отдельная подробнейшая статья.

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +    <svg width="229" height="39" viewBox="0 0 229 39" fill="none" xmlns="http://www.w3.org/2000/svg">
нам это тут прям вот архи-необходимо прям вот svg в код? Я в этом сомневаюсь. Просто изображение с текстом.

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +            Седона достаинства
Ну нет. Тут прям страница про фото и видео, а не про достоинства.

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +          <p class="stats__slogan">
Вот это и есть заголовок

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +        <header class="stats__header">
Очень странно тут видеть header. От чего он? Ни от чего. Это не шапка статьи, не шапка сайта. просто header почему-то. Я не вижу смысла в этой обертке совсем.

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +      <div class="stats__wrapper">
На самом деле и в этой обертке я также не вижу особого смысла.

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +        fill="#fff" /></svg>
А вот обертка для всего верхнего блока чтоб ему задать фоном картинку – нужна

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +    <section class="stats">
Скажу больше, эта обертка может вовсе идти до самого конца списка и даже после видео, так как весь этот блок по сути и отвечает за фото и видео и почему тут название stats честно говоря тоже не очень понятно. stats с английского – статистика. Какая тут статистика? Статистика чего? Я не вижу тут никаких чисел, никаких графиков, ничего подобного нет. Но при этом называется блок "статистика"...

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +    </section>
Не тут она должна заканчиваться а уже под видео прям. Идет заголовок, описание, список, опять заголовок, описание, видео, всё в этом одном section. Не надо плодить тонну оберток просто так. Максимум - можно заголовок описание список обернуть в отдельный section (прям сам по себе без лишних оберток) и потом ещё section с видео.

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +          <svg width="23" height="21" viewBox="0 0 23 21" fill="none" xmlns="http://www.w3.org/2000/svg">
Это чистый декоратив.

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +          <h3 class="product-content-title">Неродные просторы</h3>
И зачем это сделано как бэм блок если это часть от карточки? Заголовок только в карточке и больше нигде не реиспользуется совсем... не понятно зачем делать отдельный бэм-блок.

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +          <img src="/source/img/not-native-spaces.jpg" width="280" height="280"
За пути я молчу. всё везде исправлять. Убирать /source/ вообще НАВСЕГДА

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +    <section class="stats">
Эм... опять статистика? Убирай эту тонну оберток.

2022-11-28 18:07 UTC, captain-zsa commented on source/catalog.html
> +        <div class="main-footer__contacts contacts">
Какие тут контакты мне оч интересно... Просто хэштэг и нет тут ни email, ни адреса, ни телефона, ничего. Причем тут контакты?

2022-11-29 18:10 UTC, Bubleshmig163 commented on source/catalog.html
> +    <img src="/source/img/form-catalog-main-sedona-mountain.jpg" width="320" height="158" alt="Sedona mountain">
удалить все картинки декоративные?

2022-11-29 18:10 UTC, Bubleshmig163 commented on source/catalog.html
> +    <a class="main-header__logo">
сделал

2022-11-29 18:11 UTC, Bubleshmig163 commented on source/catalog.html
> +            <a href="catalog.html">
поправил, торопился по этому не заметил.

2022-11-29 18:11 UTC, Bubleshmig163 commented on source/catalog.html
> +    <svg width="229" height="39" viewBox="0 0 229 39" fill="none" xmlns="http://www.w3.org/2000/svg">
svg тоже убрать пока?

2022-11-29 18:12 UTC, Bubleshmig163 commented on source/catalog.html
> +          <svg width="23" height="21" viewBox="0 0 23 21" fill="none" xmlns="http://www.w3.org/2000/svg">
тоже убрать?

2022-11-29 18:14 UTC, Bubleshmig163 commented on source/catalog.html
> +          <h3 class="product-content-title">Неродные просторы</h3>
тут не понял

2022-11-29 18:14 UTC, Bubleshmig163 commented on source/catalog.html
> +          <img src="/source/img/not-native-spaces.jpg" width="280" height="280"
убрал

2022-11-29 18:15 UTC, Bubleshmig163 commented on source/catalog.html
> +    <section class="stats">
да по всем станицам думаю над классами потому что времени не хватает, не успеваю за курсом

2022-11-29 18:22 UTC, Bubleshmig163 commented on source/catalog.html
> +        <div class="main-footer__contacts contacts">
Убрал див этот <div class="main-footer__contacts contacts"> полностью

2022-12-02 12:02 UTC, babtshe requested changes
Привет, хорошо бы поправить замечания наставника по домашке. 
И напиши мне в телеграм: https://t.me/PlayingWithFire

2022-12-04 13:51 UTC, babtshe requested changes

2022-12-04 13:51 UTC, babtshe commented on source/catalog.html
> +      <img src="img/logotype-cuty-of-sedona.svg" width="185" height="96" alt="City of Sedona">
здесь и далее проверь опечатки в путях

2022-12-04 13:51 UTC, babtshe commented on source/catalog.html
> +            <a href="#">
страница не должна ссылаться сама на себя, href тут лишний

2022-12-04 13:51 UTC, babtshe commented on source/catalog.html
> +        <ul class="main-nav__list site-list">
site-list не очень хорошее название для блока навигации. Если не знать контекст, никогда не догадаешься что это именно навигация, а не какой-то список сайтов

2022-12-04 13:51 UTC, babtshe commented on source/catalog.html
> +    <h1 class="visually-hidden">Седона</h1>
в данном случае в заголовке первого уровня как раз и будет "Фото и Видео", это же не главная страница

2022-12-04 13:51 UTC, babtshe commented on source/catalog.html
> +            Фото и видео
зачем делать скрытый заголовок, а потом его же текстом дублировать? Какая от этого польза?

2022-12-04 13:51 UTC, babtshe commented on source/catalog.html
> +            Не можете решиться на путешествие <br>из-за курса? Фотографии помогут вам <br>забыть о политике и экономике.
см [критерий](https://up.htmlacademy.ru/adaptive/27/criteries#b2)

2022-12-04 13:51 UTC, babtshe commented on source/form.html
> +            Седона достаинства
❗️

2022-12-04 13:51 UTC, babtshe commented on source/form.html
> +      <form action="" class="order__form">
 хорошо бы указать тип формы и куда отправляться. Данные можно найти в ТЗ к проекту

2022-12-04 13:51 UTC, babtshe commented on source/form.html
> +            <input type="checkbox" name="attractions" value="email" checked>
здесь и далее хорошо бы value поправить

2022-12-04 13:51 UTC, babtshe commented on source/form.html
> +        <input class="field" placeholder="Опишите подробно все свои восторги " type="text" required>
обрати внимание, тут многострочное поле ввода

2022-12-04 13:51 UTC, babtshe commented on source/index.html
> +            Седона достаинства
❗️

2022-12-04 13:51 UTC, babtshe commented on source/index.html
> +              НАСТОЯЩИЙ ГОРОДОК
Прописные буквы задаются в стилях

2022-12-04 13:51 UTC, babtshe commented on source/index.html
> +              — №1 —
это точно не список определений

2022-12-04 14:32 UTC, Bubleshmig163 commented on source/form.html
> +      <form action="" class="order__form">
что то я не нашел ТЗ
 к макету

2022-12-04 14:33 UTC, Bubleshmig163 commented on source/catalog.html
> +            Не можете решиться на путешествие <br>из-за курса? Фотографии помогут вам <br>забыть о политике и экономике.
тут не понял все <p> заменить на <br>

2022-12-04 14:34 UTC, Bubleshmig163 commented on source/form.html
> +            <input type="checkbox" name="attractions" value="email" checked>
value имя такое же поставить как и у name?

2022-12-05 07:28 UTC, babtshe approved these changes

2022-12-05 07:28 UTC, babtshe commented on source/catalog.html
>            </p>
можно сразу заголовок сделать

2022-12-05 07:28 UTC, merged